on:
  pull_request:
  push:
    branches:
      - main


name: Check and Lint

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt-get install mold clang lld -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output
